const DATA = {
  "categories":
    [{
      "category": {
        "isExpanded": false,
        "subcategories":
          [
            {
              "items": ["Beef (93/7 ground)", "Bison", "Filet Mignon (trim fat)", "Kangaroo", "Sirloin (ground)", "Sirloin Strip Steak", "Veal (Ground)", "Venison"],
              "subCategoryname": "Beef",
            },
            { "items": ["Lean Loin Chop", "Lean Pork Loin"], "subCategoryname": "Pork" },
            { "items": ["Chicken", "Cornish Game Hen", "Emu", "Ostrich", "Quail", "Turkey"], "subCategoryname": "Poultry" }],
        "quote": "", "protip": "", "imagePath": "https://i.pinimg.com/originals/f8/de/58/f8de587f43fe3513de678cc25c4b6806.png", "localImagePath": "protein", "categoryName": "Lean Protein", "colorCode": "#F168A4",
        "servingSize": "4 Oz Servings", 
      }
    }
      , { "category": {"isExpanded": false, "subcategories": [{ "items": ["Alaskan King Crab", "Cod", "Flounder", "Grouper", "Halibut", "Lobster", "Mahi Mahi", "Monkfish", "Orange Roughy", "Perch", "Pike", "Salmon *", "Scallops", "Sea Bass", "Shrimp", "Swordfish", "Tilapia", "Walleye", "White Roughy"], "subCategoryname": "" }], "quote": "*When eating Salmon, reduce the amount to 3oz", "protip": "Lean Lunch Meat (93% lean or more) is appropriate", "imagePath": "https://thumbs.dreamstime.com/b/fresh-seafood-blue-background-border-ice-copy-space-retro-toned-117734519.jpg", "localImagePath": "seaFood", "categoryName": "Sea Food", "colorCode": "#689AF1", "servingSize": "4 Oz Servings" } },
    { "category": { "isExpanded": false, "subcategories": [{ "items": ["Banana Peppers", "Bell Peppers", "Bok Choy", "Cabbage", "Celery", "Chives", "Collard Greens", "Cucumbers", "Daikon Radish", "Garlic", "Iceberg Lettuce", "Jalanpeno Peppers", "Manoah Lettuce", "Mushrooms", "Red Leaf Lettuce", "Red Onions", "Romaine Lettuce", "Sauerkraut", "Spinach", "Swiss Chard", "Tomatilio", "Tomato", "Watercress"], "subCategoryname": "Free Vegetables" }, { "items": ["Acorn Squash", "Amaranth", "Asparagus", "Belgian Endive", "Boston Bib Lettuce", "BroccoFlower", "Broccoli", "Broccolini", "Brussel Sprouts", "Butter Lettuce", "Carrots (3 oz)", "Cauliflower", "Celery Root", "Chayote Squash", "Cherry Tomatoes", "Chinese Eggplant", "Crookneck Squash", "Eggplant", "Fennel", "Fiddlehead Ferns", "Green Beans", "Horseradish Root", "Kale", "Kohlrabi", "Leeks", "Pumpkin", "Purple Asparagus", "Radicchio", "Radish Leaves", "Radishes", "Ramps (wild leeks)", "Rhubard", "Snow Peas", "Spaghetti Squash", "Sugar Snap Peas", "Summer Squash", "Sweet Dumpling Squash", "White Onion", "Zucchini"], "subCategoryname": "Non-Free Vegetables", "servingSize": "4 Oz Servings" }], "quote": "No Potatoes, Corn and Peas allowed", "protip": "", "imagePath": "https://s20427.pcdn.co/wp-content/uploads/2016/12/15-Tasty-Green-Vegetables-that-are-Great-for-Your-Health.jpg", "localImagePath": "vegetable", "categoryName": "Vegetables", "colorCode": "#14A581" } },
    { "category": { "isExpanded": false, "subcategories": [{ "items": ["Apple", "Apricot", "Bilberry", "Blackberry", "Blueberry", "Boysenberry", "Cherry", "Cloud Fruit", "Cranberry", "Currant", "Damson", "Dragon Fruit", "Elderberry", "Grapefruit", "Honeyberry", "Huckleberry", "Kiwi", "Kumquat", "Lemon", "Lime", "Loquat", "Melon (all varieties)", "Mulberry", "Orange (all varieties)", "Papaya", "Pineberry", "Plum", "Pluot", "Pomello", "Purple Mangosteen", "Quince", "Raspberry", "Sapodilla", "Star Fruit", "Strawberry", "Tamarillo"], "subCategoryname": "Approved Fruit" }], "quote": "", "protip": "For maximum results it is optional NOT to have fruits", "categoryName": "Fruits", "imagePath": "https://th.bing.com/th/id/R3c8fde888c25edc549de79a83e4a27e9?rik=99HjFX1jGxYuYg&riu=http%3a%2f%2fmoderndaybrownmom.com%2fwp-content%2fuploads%2f2015%2f06%2fplantsforhumanhealth-ncsu-edu.jpg&ehk=Ld3XhFEexiJ0%2f2bTG0q7qoiFayHcqAse1lbZX6V2lEA%3d&risl=&pid=ImgRaw", "localImagePath": "fruits", "colorCode": "#F96565", "servingSize": "3 Oz Servings" } },
    { "category": { "isExpanded": false, "subcategories": [{ "items": ["Any spices without sugar", "Bragg's Amino Acids (alternative to soy sauce)", "Chicken, vegetable, or beef broth (low sodium)", "Leamon & Lime Juice", "Water or balsamic vinegar (flavored) with no oil added", "Worcestershire sauce"], "subCategoryname": "" }], "quote": "", "protip": "", "categoryName": "Alternate ingredients to fats", "imagePath": "https://th.bing.com/th/id/OIP.QOkdqKDMH-O6WxrHmwWyCgHaEK?w=329&h=184&c=7&o=5&dpr=1.5&pid=1.7", "localImagePath": "fats", "colorCode": "#FFCA5E" } },
    { "category": { "isExpanded": false, "subcategories": [{ "items": ["0-calorie sauces and dressings [Walden Farms/ Hendricks]", "0-calorie coffee creamer", "Braggs Amino Acids", "Cayenne powder/pepper", "Chinese 5 spice", "Citrus juice (lemon, lime, orange …tsp. not cups)", "Crushed red pepper", "Frank’s Hot Sauce or Buffalo Wing Sauce", "Garlic (fresh or powder)", "Herbs (fresh or dried)", "Lemon pepper", "Montreal seasoning", "Pepper (black, green, white and pink)", "'No sugar added' Pico de Gallo", "Pink Himalayan Salt", "Soy sauce (low sodium)", "Stevia sweetener (any flavor)", "Tabasco", "Vinegar (0-Sugar)"], "subCategoryname": "" }], "quote": "", "protip": "", "categoryName": "Sauces and Seasonings", "imagePath": "https://th.bing.com/th/id/OIP.XihESnFwTvA1BujRmFsGVgHaLF?w=127&h=189&c=7&o=5&dpr=1.5&pid=1.7", "localImagePath": "sauces", "colorCode": "#E95353" } }]
}

export default DATA
